
/**
 * Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter 
at a random position.
Find the letter that was added in t.
 */
public class FindDifference
{
  public static void main() {
        int i;
        String s = "hello";
        String t = "heillo";
        
        System.out.println(findTheDifference(s,t));
        System.out.println(findTheDifference("merpv","mevrpe"));

  }
  
  public static char findTheDifference(String s, String t) {
      char answer = 'o';
      int index = 0;
      for(int i = 0; i < t.length(); i++) { 
        char holder = t.charAt(i); 
        index = s.indexOf(holder);
        if(index == -1) {
            return holder;
        }
      }
      for(int i = 0; i < t.length(); i++) {
        for(int j = i+1; j < t.length(); j++) {
            if (t.charAt(i) == t.charAt(j)) {
                return t.charAt(i);
            }
        }
      }
      return answer; 
  }
}
